### ISSUE TITLE
Fix mol_graph.py bug when loading custom dataset

### ISSUE THREAD

**Issue by bobbyjudd** [bobbyjudd/rexgen_direct#1]
In rexgen_direct/core_wln_global/nntest_direct.py the line:
`smiles2graph_batch = partial(_s2g, idxfunc=lambda x:x.GetIntProp('molAtomMapNumber') - 1)`

The lambda body `x.GetIntProp('molAtomMapNumber')` tries to reference an integer property for and Atom object.  See the RDKit docs about this property: [https://www.rdkit.org/docs/RDKit_Book.html?highlight=molatommapnumber#magic-property-values](url)

When running the custom Patent DB dataset, this code generates a KeyError:

>   File "nntest_direct.py", line 191, in <module>
    bindex_to_o = {val:key for key, val in bo_to_index.iteritems()}
AttributeError: 'dict' object has no attribute 'iteritems'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/bobby/anaconda3/envs/my-rdkit-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/bobby/anaconda3/envs/my-rdkit-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "nntest_direct.py", line 168, in read_data
    src_tuple = smiles2graph_batch(src_batch)
  File "/home/bobby/projects/ucla/cs260/final_proj/rexgen_direct/rexgen_direct/core_wln_global/mol_graph.py", line 143, in smiles2graph_list
    res = list(map(lambda x:smiles2graph(x,idxfunc), smiles_list))
  File "/home/bobby/projects/ucla/cs260/final_proj/rexgen_direct/rexgen_direct/core_wln_global/mol_graph.py", line 143, in <lambda>
    res = list(map(lambda x:smiles2graph(x,idxfunc), smiles_list))
  File "/home/bobby/projects/ucla/cs260/final_proj/rexgen_direct/rexgen_direct/core_wln_global/mol_graph.py", line 81, in smiles2graph
    idx = idxfunc(atom)
  File "nntest_direct.py", line 52, in <lambda>
    smiles2graph_batch = partial(_s2g, idxfunc=lambda x:x.GetIntProp('molAtomMapNumber') - 1)
KeyError: 'molAtomMapNumber'

The included preprocessed datasets (train.txt.proc, test.txt.proc, valid.txt.proc) do not generate this error, however both datasets have been preprocessed by the prep_data.py script.

Need to determine what is unique to the custom dataset that is causing that is causing the error.

**Comment by bobbyjudd** [comment]
Fixed with commit 203ea624b4a2acb4bb644e5e5aed334d08e5d479
